### ISSUE TITLE
ROTARY_SCALE 2 small problem

### ISSUE THREAD

**Issue by Frank-Bemelman** [RolandRust/HaniMandlWroom#1]
Hi there!

Tried your software. My rotary encoder gives 2 steps per click. 
So I adjusted #define ROTARY_SCALE 2

When set to 1, it is difficult to navigate the setup menu, as it makes two steps per click of the rotary knob.
When set to 2, the navigation makes nice steps, but only the 4 first items are reachable.

So, around line #2970, I changed as shown below. Now, the full menu is accesible. 

BTW, I also changed the direction of the knob, it seems to me that -1 for the step value gives an unnatural behaviour,
but I guess this might be personal. For me, a clockwise rotation should select in downwards fashion.

initRotaries(SW_MENU, lastpos, -1, MenuepunkteAnzahl, 1);
  while (modus == MODE_SETUP and (digitalRead(switch_setup_pin)) == HIGH) {
    if (rotaries[SW_MENU].Value < 0) {
      rotaries[SW_MENU].Value = (MenuepunkteAnzahl * ROTARY_SCALE) - 1;
    }
    else if (rotaries[SW_MENU].Value > ((MenuepunkteAnzahl * ROTARY_SCALE) - 1)) {
      rotaries[SW_MENU].Value = 0;
    }

Keep up the good work,
Cheers.
Frank

**Comment by RolandRust** [comment]
Hello,
thx for the Input. 
I tested the Rotary only with the KY-040. Maybe I should also order a HW-040 RSW.
I'll implement your changes and will test the Program.  You are right. The HW-040 makes 2 Input Signals per one step, so You will never reach the end of the Menu. 
BR
Roli

**Comment by RolandRust** [comment]
Should be now fixed in the Developer Branch. But not tested.

**Comment by RolandRust** [comment]
Should be solved with the new release

**Comment by RolandRust** [comment]
Should be solved with the new release
