### ISSUE TITLE
HaniMandl upstream maintenance

### ISSUE THREAD

**Issue by amotl** [RolandRust/HaniMandlWroom#2]
Dear Roland,

thank you for your excellent work over here, and a belated happy new year (it is still January, right?). ;]

We are finally and gradually getting back to maintaining the original code and project [^1], and would like to get in touch with you about it.

- https://github.com/hiveeyes/hani-mandl/issues/40

Coming from [^2], where you are also receiving praise from the community, would you be up to upstreaming your changes to the canonical spot, or do we have the permission to cherry-pick corresponding improvements?

We would love to build up some development nucleus together, but of course it is totally up to you. In any case, we appreciate any kind of help and support. Let us also know if you need any mutual support, and keep up the good work.

With kind regards,
Andreas.

[^1]: https://github.com/hiveeyes/hani-mandl
[^2]: https://community.hiveeyes.org/t/getting-hanimandl-out-into-the-world-hanimandl-raus-in-die-grosse-welt-werfen/5193

**Comment by RolandRust** [comment]
Sent a eMail to amotl.

**Comment by RolandRust** [comment]
Hi Andreas, yes, that is a good Idea, I love the open source development. And also I wish to Understand what should be the differents from the Comercial Version and the Open source version. till know I realiced what was in my "Brian" based on your Hanimandel Code.

**Comment by amotl** [comment]
>> Join the crew at [community.hiveeyes.org](https://community.hiveeyes.org/)?
>
> That is a good Idea, I love the open source development.

Excellent. Feel free to join any time.

> Also I wish to understand about the differences between the commercial version and the open source version.

The commercial variant by @andreash-esp, demonstrated at https://hanimandl.de/, is another fork of the original version by Marc Vasterling. It is probably much more mature than the upstream FOSS variant, so the one maintained by Clemens|Hiveeyes is a bit left behind. Because Andreas' variant is closed source, we can't tell much about what's exactly inside, but we believe up until now it has been totally rewritten compared to the original.

**Comment by amotl** [comment]
Thank you for joining, Roland.

At [Getting HaniMandl out into the world / Hanimandl raus in die grosse Welt werfen](https://community.hiveeyes.org/t/getting-hanimandl-out-into-the-world-hanimandl-raus-in-die-grosse-welt-werfen/5193), you already earned much praise, so feel free to share your email to me with the community right away, either on this discussion thread, or on behalf of a separate thread/topic within the [HaniMandl category](https://community.hiveeyes.org/c/hanimandl/78).

I think [@roidesreines](https://community.hiveeyes.org/u/roidesreines/summary) will be happy to see you around, and I also wish you a pleasant stay. Have fun! 

Thanks again, closing this.
