### ISSUE TITLE
Schematic pin numbers

### ISSUE THREAD

**Issue by salmancina** [RolandRust/HaniMandlWroom#3]
Hi Roland,
Thank you very much for your excellent project.
I think there are some minor labelling issues on the schematic diagrams. The pin numbering on the esp32 from pins 20 to 38 are running from top to bottom rather than bottom to top.
Also the +3 and GND are transposed on the HX711 on some of the sheets.
Regards, Sal Mancina

**Comment by RolandRust** [comment]
Hi Sal Mancina,
jepp, the ESP32 isn't nice nummered. I can change them if I change the schematic, but this symbol is not drawed nice. It was created for hand soldering. For the PCB version i would the pins group by function :-).
The pins for the HX711 can be confused.  As I started with the wired version i did not look to the pin number of the connector. The folder PCB  is an sepparat project.

**Comment by salmancina** [comment]
Hi Roland,

Good to hear from you. I used your original project as the basis of my
build. Thank you very much for making it available. I am following your
development branch on GitHub and will try it when you think it is mature.

If it helps in any way I have attached a copy of my ino file. All the
onscreen displays are now in English. Perhaps you can try it as I have
changed some of the onscreen items to (I hope) make things clearer.

I haven't implemented the INA219, counters or multiple users so those parts
are not translated. Also the error messages are not translated yet, perhaps
that will come next.

Regards, Sal
