### ISSUE TITLE
Add Honey Comb to jar

### ISSUE THREAD

**Issue by Pukkahq** [RolandRust/HaniMandlWroom#7]
An Idea.

Have an option to tar the jar, add some honey comb and then fill the jar, so the honey comb and honey weights 500g total.

**Comment by RolandRust** [comment]
I can have a look if I find time for this idea. The Code needs only a break after the Tare from the jar and maybe some variable in the settings that you can tell the HM that you want tu use this function.

**Comment by RolandRust** [comment]
working on it

**Comment by RolandRust** [comment]
is now implemented in the development branch. You can turn this function on/off in the automatic setup menu

**Comment by RolandRust** [comment]
close task. get no response if it was the function he want

**Comment by RolandRust** [comment]
close
