### ISSUE TITLE
scaletime not declared - when compiling with isDebug 5

### ISSUE THREAD

**Issue by KarlEffinger** [RolandRust/HaniMandlWroom#8]
When compiling the source with
`#define isDebug 5`
there is a compilation error: `'scaletime' was not declared in this scope`
The error is caused by line 3588: `      Serial.print(" Dauer ");           Serial.print(millis() - scaletime);`
which belongs to procedure `void processAutomatik(void)`
"Scaletime" is defined once in line 2864 of procedure `void setupINA219(void)`, but not available outside.

**Comment by RolandRust** [comment]
I will fix it. THX for the report

**Comment by RolandRust** [comment]
Should be fixed
